version: '3.0'
services:
  mysql8:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "123654"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime:ro
