version: "3.0"
services:
  redis:
    image: redis:6.0.6
    restart: always
    container_name: redis_6.0.6
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 16379:6379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data/:/etc/redis/data
      - ./logs:/etc/redis/logs
    command: ["redis-server","/etc/redis/redis.conf"]
