version: "3.0"
services:
  redis:
    image: redis:5.0.5
    restart: always
    container_name: redis_5.0.5
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data/:/etc/redis/data
      - ./logs:/etc/redis/logs
    command: ["redis-server","/etc/redis/redis.conf"]
